course/urls.py
from django.conf.urls import url
# from . import views
from views import CitiesList, CityCreate, CityUpdate, CityDelete
from views import TeacherList, TeacherCreate, TeacherUpdate, TeacherDelete
from views import IndexView, TeacherHomeView, StudentHomeView

app_name = 'course'

urlpatterns = [
    # HOME PAGE
    url(r'home/$', IndexView.as_view(), name='index'),
    url(r'home-teacher/(?P<pk>[0-9]+)$', TeacherHomeView.as_view(), name='teacher-home'),
    url(r'home-student/(?P<pk>[0-9]+)$', StudentHomeView.as_view(), name='student-home'),
    # Home Page ends

    # Cities URLS BEGINS
    url(r'cities/$', CitiesList.as_view(), name='cities-list'),
    url(r'city/add/$', CityCreate.as_view(), name='city-add'),
    url(r'city/(?P<pk>[0-9]+)/$', CityUpdate.as_view(), name='city-update'),
    url(r'city/(?P<pk>[0-9]+)/delete/$', CityDelete.as_view(), name='city-delete'),
    # Cities ends

    # TEACHER URLS BEGINS
    url(r'teacher/$', TeacherList.as_view(), name='teacher-list'),
    url(r'teacher/add/$', TeacherCreate.as_view(), name='teacher-add'),
    url(r'teacher/(?P<pk>[0-9]+)/$', TeacherUpdate.as_view(), name='teacher-update'),
    url(r'teacher/(?P<pk>[0-9]+)/delete/$', TeacherDelete.as_view(), name='teacher-delete')
    # TEACHER ENDS

]

course/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class City(models.Model):
    name = models.CharField(max_length=30)
    postal_code = models.CharField(max_length=30)

    def __str__(self):              # __unicode__ on Python 2
        return self.name + self.postal_code


class Home(models.Model):
    street = models.CharField(max_length=30)
    name = models.CharField(max_length=30)
    city = models.ForeignKey(
        'City',
        on_delete=models.SET_NULL, null=True
    )

    def __str__(self):              # __unicode__ on Python 2
        return self.street + self.name


class Person(models.Model):
    # I left out name and surname because I will use the User module
    # name = models.CharField(max_length=30)
    # surname = models.CharField(max_length=30)
    user = models.OneToOneField(User, null=True)
    dni = models.SmallIntegerField()
    home = models.ForeignKey(
        'Home',
        on_delete=models.SET_NULL, null=True
    )
    # members = models.ManyToManyField(People)

    def __str__(self):              # __unicode__ on Python 2
        return self.dni

    def __unicode__(self):
        return u'%s' % (self.dni)


class Course(models.Model):
    name = models.CharField(max_length=30)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)

    def __str__(self):
        return self.name


class Career(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Student(Person):
    file = models.SmallIntegerField()
    enrolled_courses = models.ManyToManyField(Course)
    Careers = models.ManyToManyField(Career)

    def __str__(self):
        return str(self.file)


class Teacher(Person):
    degree = models.CharField(max_length=30)
    teaching_courses = models.ManyToManyField(Course)

    # TODO: Falta probar devolver cosas de la super clase
    def __str__(self):
        return self.degree

course/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from models import City, Teacher, Home, Person


class CityCreateForm():

    def __init__(self, values):
        """Metodo init."""
        self.name = values.get('name', None)
        self.postal_code = values.get('postal-code', None)

    def is_valid(self):
        """Metodo is valid."""
        if self.name and self.postal_code:
            if City.objects.all().filter(name=self.name).count():
                self.error = "La ciudad ya existe, elija otro nombre"
                return False
            elif self.postal_code == 0:
                self.error = "El codigo postal no puede ser 0"
                return False
            return True

        self.error = "Todos los campos son obligatorios"
        return False

    def save(self):
        """Metodo save."""
        city = City(
            name=self.name,
            postal_code=self.postal_code)
        city.save()
        return city


class CityUpdateForm(CityCreateForm, object):

    def __init__(self, values, id):
        """Metodo init."""
        super(CityUpdateForm, self).__init__(values)
        self.id = id
        self.cancel = values.get('cancel', None)

    def is_valid(self):
        """Metodo is_valid."""
        if self.cancel:
            return False
        if self.name and self.postal_code:
            if self.postal_code == 0:
                self.error = "El codigo postal no puede ser 0"
                return False
            return True

        self.error = "Todos los campos son obligatorios"
        return False

    def save(self):
        """Metodo save."""
        city = City.objects.get(pk=self.id)
        city.name = self.name
        city.postal_code = self.postal_code
        city.save()
        return city


class CityDeleteForm():

    def __init__(self, values, id):
        """Metodo init."""
        self.id = id
        self.cancel = values.get('cancel', None)

    def is_valid(self):
        """Metodo is_valid."""
        if self.cancel:
            return False
        if City.objects.get(pk=self.id):
            return True
        else:
            self.error = "No existe esa ciudad"
            return False

    def save(self):
        """Metodo save."""
        city = City.objects.get(pk=self.id)
        city.delete()


class TeacherCreateForm():

    def __init__(self, values):
        """Metodo init."""
        self.name = values.get('name', None)
        self.surname = values.get('surname', None)
        self.dni = values.get('dni', None)
        self.degree = values.get('degree', None)
        self.houses = values.get('houses', None)

    def is_valid(self):
        """Metodo is_valid."""
        if self.name and self.surname and self.dni and self.degree and self.houses:
            house = Home.objects.filter(pk=self.houses)
            if not house.count() > 0:
                self.error = "La casa ingresada no existe"
                return False
            elif self.dni == 0:
                self.error = "El DNI no puede ser 0"
                return False
        return True

        self.error = "Todos los campos son obligatorios"
        return False

    def save(self):
        """Metodo save."""
        house = Home.objects.get(pk=self.houses)
        t = Teacher(
            name=self.name,
            surname=self.surname,
            dni=self.dni,
            home=house,
            degree=self.degree)
        t.save()
        return Teacher


class TeacherUpdateForm(TeacherCreateForm, object):

    def __init__(self, values, id):
        """Metodo init."""
        super(TeacherUpdateForm, self).__init__(values)
        self.id = id
        # print vars(self)

    def is_valid(self):
        """Metodo is_valid."""
        if self.name and self.surname and self.dni and self.degree:
            house = Home.objects.filter(pk=self.houses)
            if not house:
                self.error = "La casa ingresada no existe"
                return False
            elif self.dni == 0:
                self.error = "El DNI no puede ser 0"
                return False
        return True

        self.error = "Todos los campos son obligatorios"
        return False

    def save(self):
        """Metodo save."""
        house = Home.objects.get(pk=self.houses)
        t = Teacher.objects.get(pk=self.id)
        t.name = self.name
        t.surname = self.surname
        t.dni = self.dni
        t.home = house
        t.degree = self.degree
        t.save()


class TeacherDeleteForm():

    def __init__(self, values, id):
        """Metodo init."""
        self.id = id
        self.cancel = values.get('cancel', None)

    def is_valid(self):
        """Metodo is_valid."""
        if self.cancel:
            return False
        if Teacher.objects.get(pk=self.id):
            return True
        else:
            self.error = "No existe ese profesor"
            return False

    def save(self):
        """Metodo save."""
        teacher = Teacher.objects.get(pk=self.id)
        teacher.delete()


class LoginForm():

    def __init__(self, values):
        """Metodo init."""
        self.username = values.get('username', None)
        self.password = values.get('password', None)

    def is_valid(self):
        """Metodo is_valid."""
        if self.username and self.password:
            # ver lo de que el usuario exista y tenga la contraseña bien
            return True
        else:
            self.error = "No existe ese profesor"
            return False

    def save(self):
        """Metodo save."""

course/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# from django.shortcuts import render
# from django.http import HttpResponse

from course.models import City, Teacher, Course, Student
from course.models import Home
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from .forms import CityCreateForm, CityUpdateForm, CityDeleteForm
from .forms import TeacherCreateForm, TeacherUpdateForm, TeacherDeleteForm
from django.conf import settings
import datetime
import calendar
# from braces.views import LoginRequiredMixin


# CityViews Begin


class CityCreate(CreateView):
    model = City
    fields = ['name']
    # form_class = CityCreateForm
    template_name = 'course/city_form.html'

    def post(self, request, *args, **kwargs):
        """Metodo post."""
        ctx = {}
        form = CityCreateForm(request.POST)
        if form.is_valid():
            form.save()
            # <process form cleaned data>
            return HttpResponseRedirect(reverse_lazy('course:cities-list'))
        ctx['error'] = form.error
        return render(request, self.template_name, ctx)


class CityUpdate(UpdateView):
    model = City
    template_name = 'course/city_update.html'
    form_class = CityUpdateForm
    success_url = reverse_lazy('course:cities-list')

    def get(self, request, *args, **kwargs):
        """Metodo get."""
        print kwargs
        ctx = {}
        key = kwargs['pk']
        city = self.model.objects.get(pk=key)
        ctx['city'] = city
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        """Metodo post."""
        ctx = {}
        form = self.form_class(request.POST, kwargs['pk'])
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(self.success_url)
        ctx['error'] = form.error
        return render(request, self.template_name, ctx)


class CityDelete(DeleteView):
    model = City
    success_url = reverse_lazy('course:cities-list')
    template_name = 'course/city_confirm_delete.html'
    form_class = CityDeleteForm

    def get(self, request, *args, **kwargs):
        """Metodo get."""
        print kwargs
        ctx = {}
        key = kwargs['pk']
        city = self.model.objects.get(pk=key)
        ctx['city'] = city
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        """Metodo post."""
        ctx = {}
        form = self.form_class(request.POST, kwargs['pk'])
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(self.success_url)
        ctx['error'] = form.error
        return render(request, reverse_lazy('course:cities-delete'), ctx)


class CitiesList(ListView):
    model = City
    template_name = 'course/city_list.html'

    def get(self, request, *args, **kwargs):
        """Metodo get."""
        ctx = {}
        ctx['cities'] = self.model.objects.all()
        return render(request, self.template_name, ctx)

# CityViews End

# TeacherViews Begin


class TeacherList(ListView):
    model = Teacher
    template_name = 'course/teacher_list.html'

    def get(self, request, *args, **kwargs):
        """Metodo get."""
        ctx = {}
        ctx['teachers'] = self.model.objects.all()
        return render(request, self.template_name, ctx)


class TeacherCreate(CreateView):
    model = Teacher
    form_class = TeacherCreateForm
    template_name = 'course/teacher_form.html'
    success_url = reverse_lazy('course:teacher-list')

    def get(self, request, *args, **kwargs):
        """Metodo get."""
        ctx = {}
        ctx['houses'] = Home.objects.filter()
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        """Metodo post."""
        ctx = {}
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(self.success_url)
        ctx['error'] = form.error
        return render(request, self.template_name, ctx)


class TeacherUpdate(UpdateView):
    model = Teacher
    form_class = TeacherUpdateForm
    template_name = 'course/teacher_update.html'
    success_url = reverse_lazy('course:teacher-list')

    def get(self, request, *args, **kwargs):
        """Metodo get."""
        print kwargs
        ctx = {}
        ctx['houses'] = Home.objects.all()
        key = kwargs['pk']
        teacher = self.model.objects.get(pk=key)
        ctx['teacher'] = teacher
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        """Metodo post."""
        ctx = {}
        form = self.form_class(request.POST, kwargs['pk'])
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(self.success_url)
        ctx['error'] = form.error
        return render(request, self.template_name, ctx)


class TeacherDelete(DeleteView):
    model = Teacher
    success_url = reverse_lazy('course:teacher-list')
    template_name = 'course/teacher_confirm_delete.html'
    form_class = TeacherDeleteForm

    def get(self, request, *args, **kwargs):
        """Metodo get."""
        ctx = {}
        key = kwargs['pk']
        teacher = self.model.objects.filter(pk=key)
        if teacher.count() > 0:
            ctx['teacher'] = teacher[0]
        else:
            ctx['no_teacher'] = True
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        """Metodo post."""
        ctx = {}
        form = self.form_class(request.POST, kwargs['pk'])
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(self.success_url)
        ctx['error'] = form.error
        return render(request, reverse_lazy('course:cities-delete'), ctx)

# TeacherViewsEnd

# home view start


class IndexView(ListView):

    def get(self, request, *args, **kwargs):
        """Metodo get."""
        user = request.user
        if request.user.is_authenticated:
            if 'teacher' in user.groups.all().values_list('name', flat=True):
                return HttpResponseRedirect(reverse_lazy('course:teacher-home', kwargs={'pk': user.pk}))
            if 'student' in user.groups.all().values_list('name', flat=True):
                return HttpResponseRedirect(reverse_lazy('course:student-home', kwargs={'pk': user.pk}))
        else:
            return HttpResponseRedirect(settings.LOGIN_URL)


class TeacherHomeView(ListView):
    template_name = 'teacher_home.html'

    def get(self, request, *args, **kwargs):
        """Show teacher-home page."""
        # pk = request.user.pk
        print 'llegue al teacher-home'


class StudentHomeView(ListView):
    template_name = 'student_home.html'

    def starting_courses(self):
        """Return the courses that start in this month."""
        today = datetime.date.today()
        first_day_month = datetime.date(today.year, today.month, 1)
        range_month = calendar.monthrange(today.year, today.month)
        last_day_month = datetime.date(today.year, today.month, range_month[-1])
        return Course.objects.filter(start_date__range=[first_day_month, last_day_month])

    def enrolled_courses(self, pk):
        """Return the enrolled courses of the user received as parameter."""
        s = Student.objects.get(user__pk=pk)
        return s.enrolled_courses.all()

    def get(self, request, *args, **kwargs):
        """Show student-home page."""
        starting_courses = self.starting_courses()
        pk = request.user.pk
        enrolled_courses = self.enrolled_courses(pk)
        print 'llegue al student-home'

# home views end

course/templates/course/city_confirm_delete.html
{% if no_city %}
	<h1> No existe una ciudad para la pk ingresada </h1>
{% else %}
	<h1>Esta seguro de borrar la ciudad:<br>
	{{city.name}} {{city.pk}}</h1>
	<br>
	<br>
	<div class=error>{{error}}</div>
	<br>
	<br>
	<form method="post">
	    {% csrf_token %}
	 	<input type="submit" name="confirm" value="guardar">
	 	<input type="submit" name="cancel" value= "cancelar">
	</form>
{% endif %}

course/templates/course/city_form.html
<h1>Agregando nueva Ciudad</h1>
<br>
<br>
<div class=error>{{error}}</div>
<br>
<br>

<form method="post">
    {% csrf_token %}
 
    Nombre: 
    <input type="text" name="name">
    <br>
    Codigo-postal: 
    <input type="number" name="postal-code">
    <br>
    <input type="submit" value="guardar">
</form>

course/templates/course/city_list.html
<h2>Cities</h2>
<!--<ul>
   {% for city in object_list %}
      <li>{{ city.name }} {{city.postal__code}}</li>
   {% endfor %}
</ul>-->
<table>
	<tr>
		<th>Ciudad </th> <th>Codigo postal </th> <th>ID</th><th>acciones</th> 
	</tr>
   {% for city in cities %}
   <tr>
      <td>{{ city.name }}</td><td>{{city.postal_code}}</td><td>{{city.pk}}</td>
      <td><a href="{% url 'course:city-update' city.pk %}">Editar</a>
         <a href="{% url 'course:city-delete' city.pk %}">Eliminar</a></td>
   </tr>
   {% endfor %}
</table>
<br>
<br>
<a href="{% url 'course:city-add' %}">Agregar ciudad </a>

course/templates/course/city_update.html
{% if no_city %}
	<h1> No existe una ciudad para la pk ingresada </h1>
{% else %}
	<h1>Actualizando ciudad {{city.name}} {{city.pk}}</h1>
	<div class=error>{{error}}</div>
	<br>
	<br>
	<form method="post">
	    {% csrf_token %}
	 
	    Nombre: 
	    <input type="text" name="name" value="{{city.name}}">
	    <br>
	    Codigo-postal: 
	    <input type="number" name="postal-code" value="{{city.postal_code}}">
	    <br>
	    <input type="submit" value="guardar">
	</form>
{% endif %}

course/templates/course/index.html
<h3>HOLA!</h3>

course/templates/course/teacher_confirm_delete.html
{% if no_teacher %}
	<h1> No existe un profesor para la pk ingresada </h1>
{% else %}
	<h1>Esta seguro de borrar el profesor:<br>
	{{teacher.name}} {{teacher.pk}}</h1>
	<br>
	<br>
	<div class=error>{{error}}</div>
	<br>
	<br>
	<form method="post">
	    {% csrf_token %}
	 	<input type="submit" name="confirm" value="guardar">
	 	<input type="submit" name="cancel" value= "cancelar">
	</form>
{% endif %}

course/templates/course/teacher_form.html
<h1>Agregando nuevo Docente</h1>
<br>
<br>
<div class=error>{{error}}</div>
<br>
<br>

<form method="post">
    {% csrf_token %}
 
    Nombre: 
    <input type="text" name="name">
    <br>
    Apellido:
    <input type="text" name="surname">
    <br>
    DNI: 
    <input type="number" name="dni">
    <br>
    Titulo:
    <input type="text" name="degree">
    <br>
    Casa:
    <select name="houses">
    	{%for house in houses%}
  			<option value="{{house.pk}}">{{house.name}}</option>
  		{% endfor %}
    	}
  	</select> 
  	<br>
  	<br>
    <input type="submit" value="guardar">
</form>

course/templates/course/teacher_list.html
<h2>Teachers</h2>
<table>
<tr>
<th> Nombre </th>
<th>Apellido</th>
<th>Id</th>
<th>Acciones</th>

</tr>
   {% for teacher in teachers %}
      <tr>
      	<td>{{ teacher.name }}</td>
      	<td>{{teacher.surname }}</td>
      	<td>{{ teacher.id}}</td>
      	<td><a href="{% url 'course:teacher-update' teacher.pk %}">Editar</a>
      	<a href="{% url 'course:teacher-delete' teacher.pk %}">Eliminar</a></td>
     </tr> 	
   {% endfor %}
</table>
<br><br>
<a href="{% url 'course:teacher-add' %}">Agregar profesor </a>

course/templates/course/teacher_update.html
{% if not teacher %}
  <h1> No existe un docente con la pk ingresada </h1>
{% else %}
  <h1>Editando docente {{teacher.name}}</h1>
  <br>
  <br>
  <div class=error>{{error}}</div>
  <br>
  <br>

  <form method="post">
      {% csrf_token %}
   
      Nombre: 
      <input type="text" name="name" value="{{teacher.name}}">
      <br>
      Apellido:
      <input type="text" name="surname" value="{{teacher.surname}}">
      <br>
      DNI: 
      <input type="text" name="dni" value="{{teacher.dni}}">
      <br>
      Titulo:
      <input type="text" name="degree" value="{{teacher.degree}}">
      <br>
      Casa:
       <select name="houses">
        {%for house in houses%}
          <option value="{{house.pk}}"
         {% if house.name == teacher.home.name %}selected="selected"{% endif %}>
          {{house.name}}
          </option>
        {% endfor %}
    	</select> 
    	<br>
    	<br>
      <input type="submit" value="guardar">
  </form>
{% endif %}